---
version: "3.3"

#
# docker-compose -f image/docker-compose.build.yml build
#

services:
  app:
    image: ${APP_IMAGE}:${APP_IMAGE_TAG}
    build:
      dockerfile: Dockerfile
      context: .
      args:
        SOURCE_IMAGE: "klakegg/hugo:0.79.1-ext"
        HUGO_SITE: "https://github.com/wowchemy/starter-academic.git"
